services:
  # Neo4j Database - Shared between both servers
  neo4j:
    image: neo4j:5.26.2
    container_name: graphiti-neo4j
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:7474 || exit 1",
        ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    ports:
      - "7474:7474"  # HTTP - Neo4j Browser
      - "7687:7687"  # Bolt - Database connections
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-your_secure_password}
      # Memory settings optimized for Dokploy
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
      # Network settings to reduce connection issues
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      # Connection pool settings
      - NEO4J_server_bolt_connection_pool_max_size=50
      - NEO4J_server_bolt_connection_pool_min_size=5
      # Timeout settings
      - NEO4J_server_bolt_connection_timeout=30s
      - NEO4J_server_bolt_connection_keep_alive=true
      # Logging for debugging
      - NEO4J_server_logs_default_level=INFO
      - NEO4J_server_logs_http_enabled=true
      - NEO4J_server_logs_bolt_enabled=true
    networks:
      - graphiti-network
    # Resource limits to prevent overload
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Graphiti Knowledge Server (REST API)
  graphiti-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphiti-knowledge-server
    restart: unless-stopped
    ports:
      - "8000:8000"  # REST API
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o-mini}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME:-text-embedding-3-small}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-your_secure_password}
      - PORT=8000
      - PYTHONUNBUFFERED=1
    networks:
      - graphiti-network
    volumes:
      - ./logs:/app/logs
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Graphiti MCP Server
  graphiti-mcp:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: graphiti-mcp-server
    restart: unless-stopped
    ports:
      - "8001:8000"  # MCP Server (different port to avoid conflict)
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-your_secure_password}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o-mini}
      - SMALL_MODEL_NAME=${SMALL_MODEL_NAME:-gpt-4o-mini}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.0}
      - SEMAPHORE_LIMIT=${SEMAPHORE_LIMIT:-5}
      - PYTHONUNBUFFERED=1
      - MCP_SERVER_HOST=0.0.0.0
    networks:
      - graphiti-network
    volumes:
      - ./logs:/app/logs
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local

networks:
  graphiti-network:
    driver: bridge
    # Network settings to improve stability
    driver_opts:
      com.docker.network.bridge.name: graphiti-bridge 